version: '3'
services:

  influx:
    image: influxdb:1.8
    container_name: influx
    ports:
     - "8083:8083"
     - "8086:8086"
    environment:
     - INFLUXDB_USER=user
     - INFLUXDB_USER_PASSWORD=password
     - INFLUXDB_ADMIN_ENABLED=true
     - INFLUXDB_ADMIN_USER=root
     - INFLUXDB_ADMIN_PASSWORD=password
     - INFLUXDB_DB=pantheon
    volumes:
     - "./disk/influxdb_data:/var/lib/influxdb"
    restart: always
     

  grafana:
    image: grafana/grafana
    volumes:
      - ./disk/grafana_data:/etc/grafana/provisioning/
    ports:
     - "3000:3000"
    depends_on:
     - influx
    restart: always 
